version: '3'

services:
  nodejs:
    container_name: sample
    hostname: localhost
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USERNAME: root
      DB_PASSWORD: test@123
      DB_NAME: testdb
      DB_PORT: 3306
      DB_HOSTNAME: 127.0.0.1
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - sample_backend
  
networks:
  sample_backend:
    external: true